[package]
name = "hyprclock"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
gtk4 = "0.9.0"
glib = "0.20.1"
config = "0.14.0"
serde = { version = "1.0.209", features = ["derive"] }
toml = "0.8.19"
dirs = "5.0.1"
fern = "0.6.2"
log = "0.4.22"
